seleniumhub:
  image: selenium/hub
  ports:
    - 4444:4444

firefoxnode:
  image: selenium/node-firefox-debug
  ports:
    - 5900
  links:
    - seleniumhub:hub

chromenode:
  image: selenium/node-chrome-debug
  ports:
    - 5900
  links:
    - seleniumhub:hub

# tester:
#   build: .
#   command: bundle exec cucumber
#   depends_on:
#     - firefoxnode
#   ports:
#     - 5901
